using Microsoft.AspNetCore.Hosting;
using ScottPlot;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using core8_angular_mssql.Models.dto;
using core8_angular_mssql.Helpers;

namespace core8_angular_mssql.Helpers
{
 public class SalesChartDocument : IDocument
 {
    private readonly IWebHostEnvironment _env;
    private readonly SalesReportModel _model;

    public SalesChartDocument(
        IWebHostEnvironment env,
        SalesReportModel model)
    {
        _env = env;
        _model = model;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
    public DocumentSettings GetSettings() => DocumentSettings.Default;

    public void Compose(IDocumentContainer container)
    {
        var imagePath = Path.Combine(_env.WebRootPath, "images", "logo.png");
        container.Page(page =>
        {
            page.Size(PageSizes.Legal);        
            page.Margin(1, Unit.Centimetre);
            page.Content().Column(column =>
            {
                if (File.Exists(imagePath))
                {
                    byte[] imageData = File.ReadAllBytes(imagePath);
                    column.Item().Width(150).Image(imageData);                        
                }
                column.Item().Text("Product Sales Report").FontSize(20).SemiBold();
                column.Item().PaddingTop(10).AspectRatio(2).Svg(size =>
                {
                    var plot = new ScottPlot.Plot();
                    
                    // 1. Prepare data first
                    double[] values = _model.SalesData.Select(x => x.Total).ToArray();
                    double[] positions = Enumerable.Range(0, values.Length).Select(i => (double)i).ToArray();
                    
                    string[] labels = _model.SalesData
                        .Select(x => System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.GetAbbreviatedMonthName(x.Month))
                        .ToArray();

                    // 2. Add visual elements
                    plot.Add.Bars(values);

                    // 3. Configure Axes (using the variables defined above)
                    var ticks = positions.Zip(labels, (pos, lbl) => new ScottPlot.Tick(pos, lbl)).ToArray();
                    plot.Axes.Bottom.TickGenerator = new ScottPlot.TickGenerators.NumericManual(ticks);
                    
                    plot.Axes.Margins(bottom: 0);

                    return plot.GetSvgXml((int)size.Width, (int)size.Height);
                });
            });

            page.Footer().Text(text =>
            {
                text.Span(" Date & Time Generated : ").FontSize(8);
                text.Span($" {DateTime.Now:MMMM dd, yyyy  hh:mm tt}")
                .FontSize(8)
                .Italic();
                text.Span(" , Generated by : " + "Rey Gragasin").FontSize(6);

            });

        });
    }
 }
}

public class SalesReportModel
{
    public List<SaleSummaryDto> SalesData { get; set; }
}